export async function exportToPDF(results, input) {
  try {
    // Create PDF content
    const content = `
      Identity Model Agent - Trust Report
      ===================================
      
      Address: ${input}
      Generated: ${new Date().toLocaleString()}
      
      TRUST SCORE: ${results.final.trustScore}/100
      Sybil Risk: ${results.final.sybilRisk}
      
      IDENTITY INFORMATION:
      - Name: ${results.identity.name}
      - GitHub: ${results.identity.github}
      - Twitter: ${results.identity.twitter}
      
      ZK-KYC STATUS:
      - Verified: ${results.zkKyc.verified ? "Yes" : "No"}
      - Score: ${results.zkKyc.score}/100
      
      GITHUB ACTIVITY:
      - Contributions: ${results.github.contributions}
      - Repositories: ${results.github.repos}
      
      ONCHAIN ACTIVITY:
      - Score: ${results.onchain.score}/100
      - Transactions: ${results.onchain.transactions}
      - POAPs: ${results.onchain.poaps}
      
      VERIFIABLE CREDENTIALS:
      ${results.credentials.map((cred) => `- ${cred.type} (${cred.issuer})`).join("\n")}
      
      IPFS Proof: https://ipfs.io/ipfs/${results.final.proofHash}
      
      ---
      Generated by Identity Model Agent
      Decentralized Trust Scoring for Web3
    `

    // Create blob and download
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `identity-report-${input.slice(0, 8)}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    return true
  } catch (error) {
    console.error("PDF export failed:", error)
    return false
  }
}
